version: '3.8'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1010:5000"
    volumes:
      - ./app.db:/app/app.db

volumes:
  app_data:
    driver: local
